global:
  scrape_interval: 5s
  external_labels:
    cluster: demo
    namespace: demo

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          pod: 'cadvisor'